---
kind: pipeline
type: docker
name: build

# platform:
#   os: linux
#   arch: amd64

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO}
      username:
        from_secret: username
      password:
        from_secret: password
      auto_tag: true
